### ISSUE TITLE
size change

### ISSUE THREAD

**Issue by iBasit** [KyleAMathews/react-spinkit#63]
How can we change the size to make it bigger? 

Maybe few predefined sizes would be good (small, medium, large, x-large)?

**Comment by fxfactorial** [comment]
@iBasit  this is simple CSS, 

```css
.sk-spinner {
  transform: scale(2);
}
```
